### PR TITLE
nil check for in-memory queue for NotNow

### LINKED ISSUE #983: Invalid Memory in our logs
### What version of `micromdm` are you using?
1.12.1

### What `micromdm` command did you run?
We are not 100% sure as it looks kind of random
But most of our devices just get send these:
DeviceInformation
SecurityIno
ProfileList
Restrictions

### What did you expect to see?
That the updates go through without any problem

### What did you see instead?
transport=http method=PUT status=200 proto=HTTP/1.1 host=100.64.0.157 user_agent=MDM/1.0 path="/mdm/connect?enrollmentId=660b9f2cd4aead5d25b52fae"
ts="2024/04/12 07:23:54" caller="http: panic serving 100.64.0.157:56448" msg="runtime error: invalid memory address or nil pointer dereference\ngoroutine 83 [running]:\nnet/http.(*conn).serve.func1()\n\t/usr/local/go/src/net/http/server.go:1868 +0xb9\npanic({0x968920?, 0xea87f0?})\n\t/usr/local/go/src/runtime/panic.go:920 +0x270\ngithub.com/micromdm/micromdm/platform/queue/inmem.(*QueueInMem).Next(0xc000010828, {0x40e1b8?, 0x979c00?}, {{0x0, 0x0}, {0xc0002ae4e0, 0x19}, 0x0, 0x0, {0xc000d57120, ...}, ...})\n\t/Users/administrator/Desktop/micromdm/platform/queue/inmem/inmem.go:94 +0x48a\ngithub.com/micromdm/micromdm/mdm.(*MDMService).Acknowledge(0xc000112a40, {0xaf19a0, 0xc0005f3740}, {{0xc000274270, 0x24}, {0x3864a65, 0xeddaad88a, 0x0}, {{0x0, 0x0}, ...}, ...})\n\t/Users/administrator/Desktop/micromdm/mdm/acknowledge.go:23 +0x106\ngithub.com/micromdm/micromdm/platform/remove.removeMiddleware.Acknowledge({{0xaf08b0?, 0xc00005c048?}, {0xaef558?, 0xc000112a40?}}, {0xaf19a0, 0xc0005f3740}, {{0xc000274270, 0x24}, {0x3864a65, 0xeddaad88a, ...}, ...})\n\t/Users/administrator/Desktop/micromdm/platform/remove/remove.go:58 +0x116\ngithub.com/micromdm/micromdm/platform/device.(*udidCertAuthMiddleware).Acknowledge(0xc000112a80, {0xaf19a0, 0xc0005f3740}, {{0xc000274270, 0x24}, {0x3864a65, 0xeddaad88a, 0x0}, {{0x0, 0x0}, ...}, ...})\n\t/Users/administrator/Desktop/micromdm/platform/device/udidauth.go:85 +0x1e5\ngithub.com/micromdm/micromdm/server.(*verifyCertificateMiddleware).Acknowledge(0xc000112ac0, {0xaf19a0, 0xc0005f3740}, {{0xc000274270, 0x24}, {0x3864a65, 0xeddaad88a, 0x0}, {{0x0, 0x0}, ...}, ...})\n\t/Users/administrator/Desktop/micromdm/server/devicecert.go:96 +0x185\nmain.serve.MakeServerEndpoints.MakeAcknowledgeEndpoint.func22({0xaf19a0?, 0xc0005f3740?}, {0x97ebc0?, 0xc0000fb1e0?})\n\t/Users/administrator/Desktop/micromdm/mdm/acknowledge.go:67 +0x104\ngithub.com/go-kit/kit/transport/http.Server.ServeHTTP({0xc0005e4150, 0xa5b308, 0xa5b320, {0xc0005f0450, 0x2, 0x2}, {0x0, 0x0, 0x0}, 0xa5b318, ...}, ...)\n\t/Users/administrator/go/pkg/mod/github.com/go-kit/kit@v0.13.0/transport/http/server.go:121 +0x334\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc0005f40c0, {0xaf04f0, 0xc00079c280}, 0xc0000b3b00)\n\t/Users/administrator/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1c5\nmain.serve.(*HTTPLogger).Middleware.Middleware.func23({0xaf06a0?, 0xc000268380}, 0xc0000b3b00)\n\t/Users/administrator/go/pkg/mod/github.com/groob/finalizer@v0.0.0-20170707115354-4c2ed49aabda/finalizer.go:25 +0x12e\nnet/http.HandlerFunc.ServeHTTP(0xc0001ddb20?, {0xaf06a0?, 0xc000268380?}, 0xa3459d?)\n\t/usr/local/go/src/net/http/server.go:2136 +0x29\ngithub.com/micromdm/go4/httputil.ListenAndServe.ListenAndServe.enforceHSTS.func4.func5({0xaf06a0, 0xc000268380}, 0xc0000b3b00)\n\t/Users/administrator/go/pkg/mod/github.com/micromdm/go4@v0.0.0-20240215190618-908f27575419/httputil/middleware.go:116 +0xe4\nnet/http.HandlerFunc.ServeHTTP(0x4105a5?, {0xaf06a0?, 0xc000268380?}, 0xc000268301?)\n\t/usr/local/go/src/net/http/server.go:2136 +0x29\nnet/http.serverHandler.ServeHTTP({0xaeedd8?}, {0xaf06a0?, 0xc000268380?}, 0x6?)\n\t/usr/local/go/src/net/http/server.go:2938 +0x8e\nnet/http.(*conn).serve(0xc0000feea0, {0xaf19a0, 0xc000627140})\n\t/usr/local/go/src/net/http/server.go:2009 +0x5f4\ncreated by net/http.(*Server).Serve in goroutine 52\n\t/usr/local/go/src/net/http/server.go:3086 +0x5cb"

### PR DESCRIPTION
**Pull request by jessepeterson**
fixes crash and (should) resolves #983.

### CODE REVIEW

**Review by cph-jh332 — APPROVED** [review]

**Review by korylprince — APPROVED** [review]
LGTM

**Comment by cph-jh332** [comment]
We've manually built the solution and tested it. It has resolved our issue.

**Comment by m-irfan** [comment]
I want to restrict camera using allowCamera restriction, I am sending InstallProfile command with related payload, but I am getting NotNow status from the client device, the use case is when the device screen is locked we always getting NotNow status but once unlocked the profile is installed and restrictions get applied, is this an issue or its designed to behave like this when the device is locked? (BYOD case only)

**Comment by jessepeterson** [comment]
@m-irfan generally the issue trackers/pull requests are [not for asking "how to"](https://github.com/micromdm/.github/blob/main/CONTRIBUTING.md#support--getting-help) things like this. Join us on Slack to ask these questions.

That said: yes, [`NotNow` when device is locked is normal](https://developer.apple.com/documentation/devicemanagement/handling-notnow-status-responses).

**Pull request merged**
