### PR TITLE
Added SetRecoveryLock support

### PR DESCRIPTION
**Pull request by tomaswallentinus**
It says SetFirmwarePassword on the files, but its meant to be SetRecoveryLock and VerifyRecoveryLock.

I was thinking about test files, but in what file should I put the tests?

### CODE REVIEW

**Comment by meta-github** [comment]
verify_firmware_password script is using VerifyRecoveryLock. A typo?

**Comment by jessepeterson** [comment]
When you're happy with this I would love to see some testing along the lines of how #743 was done (:heart: @korylprince).

**Comment by tomaswallentinus** [comment]
Sure thing, i need to do a DFU restore of the test machine first thing tomorrow as it got to the unknown username login after a Remove all content and settings test =)

Regards Tomas Wallentinus

**Comment by tomaswallentinus** [comment]
Everything works as expected =)

Request | Current Local Password | CurrentPassword | NewPassword | Result
-- | -- | -- | -- | --
SetRecoveryLock | empty | 1234 | test | Acknowledged, No password change
SetRecoveryLock | empty | empty | 1234 | Password changed
SetRecoveryLock | 1234 | 1234 | empty | Password removed
&nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp;
Request | Current Local Password | Password | &nbsp; | Result
VerifyRecoveryLock | empty | empty | &nbsp; | PasswordVerified=true
VerifyRecoveryLock | 1234 | empty | &nbsp; | Error, Existing recovery lock   password not provided
VerifyRecoveryLock | 1234 | 1111 | &nbsp; | PasswordVerified=false
VerifyRecoveryLock | 1234 | 1234 | &nbsp; | PasswordVerified=true

**Comment by jessepeterson** [comment]
When I checkout your branch I get:

```
$ gofmt -s -l .
mdm/mdm/internal/mdmproto/mdm.pb.go
```

Looks like that file still needs some formatting. :)

**Comment by tomaswallentinus** [comment]
It doesn't work for me. I have updated protobuf, i have removed mdm.pb.go and generated it again, but it's still gets the same format error. Why don't my gofmt see whats wrong with mdm.pb.go and why is mdm.pb.go generated with incorrect format when the other files are correct?

**Comment by tomaswallentinus** [comment]
This one is ready for production if anyone wants to review :)

**Comment by jessepeterson** [comment]
@tomaswallentinus I'm curious how you generated the `mdm.pb.go` file. When I checkout your branch and just run `go generate` it seems to make very drastic changes (what I think is a "revert" of the changes you made). If you look at the diff it even reverts the protobuf version somehow: `proto.ProtoPackageIsVersion2` from `proto.ProtoPackageIsVersion3`. Which tooling did you install to make it do that?

**Review by jessepeterson — CHANGES_REQUESTED** [review]
This generally looks good. I want to get to the bottom of the `mdm.pb.go` file changes, though. See my other comment. Once that's resolved then I think this is good to go!

**Comment by tomaswallentinus** [comment]
I have seen that as well. Is it because I use Ubuntu 20.04 instead of macOS maybe?

**Comment by jessepeterson** [comment]
I don't think its platform dependent. How did you install the protoc tools? I have:

```sh
$ which protoc
/usr/local/bin/protoc
$ protoc --version
libprotoc 3.2.0
$ go install github.com/gogo/protobuf/protoc-gen-gofast@v1.3.2
```

**Comment by tomaswallentinus** [comment]
I accualy just used: go get github.com/gogo/protobuf/protoc-gen-gofast
But I used your version install now and it generates the same file.

```
$which protoc
/usr/bin/protoc
$protoc --version
libprotoc 3.17.3
$go version
go version go1.16.5 linux/amd64
$cd mdm/mdm/internal/mdmproto
$rm mdm.pb.go
$go generate
```
And that gives me the "proto.ProtoPackageIsVersion2" line.

**Comment by tomaswallentinus** [comment]
Not even updating protoc-gen-go to: https://github.com/protocolbuffers/protobuf-go/releases v 1.26 gives me a later version number.

**Comment by jessepeterson** [comment]
Could it be a pathing issue (could you have an older protoc-gen-gofast)? My understanding is that go shells out to protoc which then shells out to protoc-gen-gfast. Could protoc be finding a different protoc-gen-gofast maybe? I can't duplicate this.

**Comment by tomaswallentinus** [comment]
Looks like it. If I run 
`sudo find . -name "protoc-gen-gofast`
I have:
```
./home/*/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/protoc-gen-gofast
./home/*/go/bin/protoc-gen-gofast
./root/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/protoc-gen-gofast
./root/go/bin/protoc-gen-gofast
./usr/share/gocode/src/github.com/gogo/protobuf/protoc-gen-gofast
./usr/bin/protoc-gen-gofast
```
I will try moving them.

**Comment by tomaswallentinus** [comment]
O-holy-night🎷 that did it.
I needed to do:
`rm /usr/bin/protoc-gen-gofast
sudo mv /home/*/go/bin/protoc-gen-gofast /usr/bin/protoc-gen-gofast`
Now the versionnumber in the file is 3.

**Review by jessepeterson — APPROVED** [review]
🎉  Glad that worked. The diff for the `.pb.go` file is more like what I expected now, too.

**Pull request merged**
