### PR TITLE
Spruce up built in webpage

### PR DESCRIPTION
**Pull request by williamtheaker**
Used CSS from https://micromdm.io

### CODE REVIEW

**Comment by williamtheaker** [comment]
Screen Shot 2021-02-05 at 4 24 24 PM

**Comment by jessepeterson** [comment]
Just curious: what does this look like on iOS & iPad? Just want to make sure it's usable there, too.

**Comment by williamtheaker** [comment]
@rylandharris was kind enough to test on iOS devices for me.
iPad 7th generation running 14.4
iPhone XR running 14.3

image0
Image from iOS

**Comment by groob** [comment]
Up to @jessepeterson if we want to merge this in. 

I'm personally not in favor, even though it looks nice. I've been encouraging people to write their own enrollment logic and not use the built in one.

**Comment by williamtheaker** [comment]
I think setting the `homepage` flag to false by default would be a better way to accomplish that than rejecting visual improvements.

**Comment by jessepeterson** [comment]
I like the idea of the nicer home page in general. But to discourage built-in enrollment use, though, what do folks think of these options:

1. Do nothing, merge as is.

2. Add a new flag, disabled by default, that disables `/mdm/enroll` endpoint (and/or turns on a 'helpful' message like "Enrollment disabled" or something.

3. Outright remove the 'Enroll a device' button/link from the *home page* (not the service itself).

4. Disable `-homepage` flag by default as @williamtheaker suggested.

I don't feel super strong about this but I'm leaning toward doing 1 and then creating a new issue for 2/3. I don't really like 4. The homepage is a nice canary when first starting up MicroMDM to tell that its working and getting a 404 right off the bat could be non-intuitive for beginners. Not that MicroMDM is all that beginner friendly, heh. :shrug:

**Comment by discentem** [comment]
> Do nothing, merge as is.
I'd be okay with this. 
> Add a new flag, disabled by default, that disables /mdm/enroll endpoint (and/or turns on a 'helpful' message like "Enrollment disabled" or something.
This is seems like a good option. Though, to be honest, I'd be surprised if there are micromdm users out there who don't rely on the enroll webpage as a fallback. 
> Outright remove the 'Enroll a device' button/link from the home page (not the service itself).
Personally, I'd like to retain this option. So I'd prefer the previously mentioned flag. 
> Outright remove the 'Enroll a device' button/link from the home page (not the service itself).
I'm also okay with this, because it retains the option to use it.

**Review by jessepeterson — APPROVED** [review]

**Review by jessepeterson — CHANGES_REQUESTED** [review]
I know it's a tiny page, but could we include some basic accessibility tags/attributes for the SVG? E.g. a title, description, etc. I just googled a few things seems like they'd be easy additions.

**Comment by jessepeterson** [comment]
Created issue #741 for limiting default enrollment capability.

**Comment by williamtheaker** [comment]
> I know it's a tiny page, but could we include some basic accessibility tags/attributes for the SVG? E.g. a title, description, etc. I just googled a few things seems like they'd be easy additions.

Good call out! I didn't take that into account at all. I ran the question by accessibility consultant @bpmcneilly and was told "it should be null - assuming MicroMDM is just gonna be the alt text anyway, and that's displayed."

**Review by jessepeterson — APPROVED** [review]
Looks good. Just update the CHANGELOG and we're good to!

**Pull request merged**
