### PR TITLE
Docs site

### PR DESCRIPTION
**Pull request by qiquanlu**
use vitepress to create a docs site

Steps to run this on local

1. install node dependency, either npm install, yarn, pnpm install works. I use pnpm becasue it's fast
```
pnpm install
```

2. start dev server, with port 8080, or default to 3000
```
pnpm docs:dev --port 8080
```

more details please see [Vitepress Deploying Guide](https://vitepress.vuejs.org/guide/deploy.html)

This docs site is WIP, only include markdowns within docs folder, I think more needed be added from the wiki.

### CODE REVIEW

**Comment by korylprince** [comment]
What would be the purpose of using Vitepress over the current docs and GitHub wiki?

**Comment by qiquanlu** [comment]
It's easier to navigate the documents than current github wiki
algolia document search can be added with a few config, currently search for something is not easy
it's still markdown files, contributor has nearly no extra work to contribute docs than what they do now
a good document is very important to any project
deploy to netlify or many other vendor can be automated by github webhook, here is one I deployed to netlify [micromdm docs demo](https://micromdm-docs.netlify.app/)

> What would be the purpose of using Vitepress over the current docs and GitHub wiki?

It's easier to navigate the documents than current github wiki
algolia document search can be added with a few config, currently search for something is not easy
it's still markdown files, contributor has nearly no extra work to contribute docs than what they do now
a good document is very important to any project
deploy to netlify or many other vendor can be automated by github webhook, here is one I deployed to netlify [micromdm docs demo](https://micromdm-docs.netlify.app/)

**Comment by discentem** [comment]
> deploy to netlify or many other vendor can be automated by github webhook, here is one I deployed to netlify [micromdm docs demo](https://micromdm-docs.netlify.app/)

Does this cost money? Who would pay the bill? 

Regardless, in my opinion this should have started as a Github Issue. I empathize with the fact that you find vitepress easier to navigate but I haven't heard feedback from any other folks that they find the docs/wiki hard to navigate or update.

**Comment by qiquanlu** [comment]
To answer your question, deploys to netlify is free(at least for the purpose of this docs site). And indeed it's personal opinion that I feel vitepress navigate better. It list all subtitles on side navigation for you without any coding. Algolia search is way better than current GitHub wiki search.

**Comment by qiquanlu** [comment]
I'm closing this PR because most feedback on this doc site is  no need, and I'm closing the demo site as well to avoid confusion.

**Pull request closed without merging**
