### PR TITLE
remove expectation of json from decodeListDeviceRequest

### PR DESCRIPTION
**Pull request by bdemetris**
testing this seems to resolve
https://github.com/micromdm/micromdm/issues/364

### CODE REVIEW

**Comment by jessepeterson** [comment]
We should still attempt to parse the JSON, though, right? Perhaps just not return an error on parsing failure (or check for a null body)? We'll need to be able to have that data when we start filtering serials in #363.

**Comment by groob** [comment]
No because GET requests should use url params not a JSON body. 

We could discuss POST vs GET but GET requests cannot have an http body. This was a bug. 

My personal preference is to implement `?page=2&per_page=20&serials=foo,bar,baz`

**Comment by jessepeterson** [comment]
Well, GET requests can technically have a body. It's just merely a convention to discard it, however. But that's fine, I'm on board with URL params. There's just no code that supports decoding them at the moment. Makes me wonder if we're we doing JSON decodes in other mdmctl GET requests, too.

**Comment by groob** [comment]
We had a bunch. I switched `/dep/devices` recently to a POST request because the GET had a body. 
 
The issue is that GET _could_ have a body but tools like `curl` discard it unless you explicitly pass custom flags. It's best to avoid it in a REST api service and use POST if the body is a must.

**Pull request merged**
